### PR TITLE
Jayesh Mahajan - Code Challenge

### PR DESCRIPTION
**Pull request by Jayesh30**

### CODE REVIEW

**Comment by Jayesh30** [comment]
When I fork the branch It has set of task - 

Add a way to delete companies
Add Custom Validation to company email
Add City State To Companies from Zip Code
Include a way to set a brand colour
Include test coverage for all your changes
Suggest a new task for this challenge

But now it has different task list.

**Comment by Jayesh30** [comment]
image

Added Delete Option

**Comment by Jayesh30** [comment]
image

Added City, State

**Comment by Jayesh30** [comment]
image

Email Validation on frontend & Backend

**Comment by Jayesh30** [comment]
Select Brand Colour

image

**Comment by jeanpaulsio** [comment]
Hi @Jayesh30 - yes you are correct - the code challenge has been updated. Sorry about the confusion. No need to redo yours.

We will be in touch via email!

**Comment by Jayesh30** [comment]
@jeanpaulsio Thanks for update.

**Pull request closed without merging**
